require("dotenv").config();
const cloudinary = require("cloudinary").v2;

cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.API_KEY,
  api_secret: process.env.API_SECRET,
});

// TODO reconfigure to:
/* 
1. use a route and controller that can be hit with postman or testing
2. change the image part to take an image from a req

*/
cloudinary.uploader.upload(
  // first param is the image passed in and is the one the function here takes
  "./images/pic.png",
  { tags: "basic_sample" },
  function (err, image) {
    console.log();
    console.log("** File Upload");
    if (err) {
      console.warn(err);
    }
    console.log(
      "* public_id for the uploaded image is generated by Cloudinary's service."
    );
    console.log("* " + image.public_id);
    console.log("* " + image.url);
    // waitForAllUploads("pizza", err, image);
  }
);
